// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"try","status":true,"description":"","parameters":{}},
{"name":"SkipTitle","status":true,"description":"指定游戏开始的场景（支持自定义的场景）","parameters":{"scene":"Scene_Map","addscript":""}},
{"name":"sakeren_eventProperty","status":true,"description":"","parameters":{}},
{"name":"custom_movement","status":true,"description":"","parameters":{}}
];
